

--DATA TO TABLES 	
INSERT INTO [CITIES] ([UPDATE_COUNTER], [NAME], [AREA])
SELECT 0, 'Sofia', 'Sofia'
WHERE NOT EXISTS (
    SELECT 1
    FROM [CITIES]
    WHERE [NAME] = 'Sofia' AND [AREA] = 'Sofia'
);
select * from CITIES
INSERT INTO [CITIES] ([UPDATE_COUNTER], [NAME], [AREA])
SELECT 0, 'Montana', 'Montana'
WHERE NOT EXISTS (
    SELECT 1
    FROM [CITIES]
    WHERE [NAME] = 'Montana' AND [AREA] = 'Montana'
);

INSERT INTO [CITIES] ([UPDATE_COUNTER], [NAME], [AREA])
SELECT 0, 'Vidin', 'Vidin'
WHERE NOT EXISTS (
    SELECT 1
    FROM [CITIES]
    WHERE [NAME] = 'Vidin' AND [AREA] = 'Vidin'
);

INSERT INTO [CITIES] ([UPDATE_COUNTER], [NAME], [AREA])
SELECT 0, 'Vraca', 'Vraca'
WHERE NOT EXISTS (
    SELECT 1
    FROM [CITIES]
    WHERE [NAME] = 'Vraca' AND [AREA] = 'Vraca'
);
--
INSERT INTO [PHONE_TYPES] ([UPDATE_COUNTER], [PHONE_TYPE])
SELECT 0, 'Mobile'
WHERE NOT EXISTS (
    SELECT 1
    FROM [PHONE_TYPES]
    WHERE [PHONE_TYPE] = 'Mobile'
);

INSERT INTO [PHONE_TYPES] ([UPDATE_COUNTER], [PHONE_TYPE])
SELECT 0, 'Work'
WHERE NOT EXISTS (
    SELECT 1
    FROM [PHONE_TYPES]
    WHERE [PHONE_TYPE] = 'Work'
);

INSERT INTO [PHONE_TYPES] ([UPDATE_COUNTER], [PHONE_TYPE])
SELECT 0, 'Home'
WHERE NOT EXISTS (
    SELECT 1
    FROM [PHONE_TYPES]
    WHERE [PHONE_TYPE] = 'Home'
);

INSERT INTO [PHONE_TYPES] ([UPDATE_COUNTER], [PHONE_TYPE])
SELECT 0, 'Stationary'
WHERE NOT EXISTS (
    SELECT 1
    FROM [PHONE_TYPES]
    WHERE [PHONE_TYPE] = 'Stationary'
);
--

INSERT INTO [PERSONS] ([UPDATE_COUNTER], [FIRST_NAME], [SECOND_NAME], [THIRD_NAME], [UCN], [CITY_ID], [ADDRESS])
SELECT 0, 'Veselin', 'Ivanov', 'Ivanov', '8923451236', (SELECT ID FROM CITIES WITH(NOLOCK) WHERE [NAME]='Sofia'), 'Treti mart 33'
WHERE NOT EXISTS (
    SELECT 1
    FROM [PERSONS]
    WHERE [FIRST_NAME] = 'Veselin' AND [SECOND_NAME] = 'Ivanov' AND [THIRD_NAME] = 'Ivanov' AND [UCN] = '8923451236'
);

INSERT INTO [PERSONS] ([UPDATE_COUNTER], [FIRST_NAME], [SECOND_NAME], [THIRD_NAME], [UCN], [CITY_ID], [ADDRESS])
SELECT 0, 'Georgi', 'Borislavov', 'Georgiev', '0423644312', (SELECT ID FROM CITIES WITH(NOLOCK) WHERE [NAME]='Montana'), 'Dunav 2'
WHERE NOT EXISTS (
    SELECT 1
    FROM [PERSONS]
    WHERE [FIRST_NAME] = 'Georgi' AND [SECOND_NAME] = 'Borislavov' AND [THIRD_NAME] = 'Georgiev' AND [UCN] = '0423644312'
);

INSERT INTO [PERSONS] ([UPDATE_COUNTER], [FIRST_NAME], [SECOND_NAME], [THIRD_NAME], [UCN], [CITY_ID], [ADDRESS])
SELECT 0, 'Tsvetelin', 'Slavov', 'Martinov', '0232548712', (SELECT ID FROM CITIES WITH(NOLOCK) WHERE [NAME]='Vidin'), 'Stara Planina 23'
WHERE NOT EXISTS (
    SELECT 1
    FROM [PERSONS]
    WHERE [FIRST_NAME] = 'Tsvetelin' AND [SECOND_NAME] = 'Slavov' AND [THIRD_NAME] = 'Martinov' AND [UCN] = '0232548712'
);

INSERT INTO [PERSONS] ([UPDATE_COUNTER], [FIRST_NAME], [SECOND_NAME], [THIRD_NAME], [UCN], [CITY_ID], [ADDRESS])
SELECT 0, 'Aleksandar', 'Kostov', 'Kostov', '9953354231', (SELECT ID FROM CITIES WITH(NOLOCK) WHERE [NAME]='Vraca'), 'Hristo Botev 82'
WHERE NOT EXISTS (
    SELECT 1
    FROM [PERSONS]
    WHERE [FIRST_NAME] = 'Aleksandar' AND [SECOND_NAME] = 'Kostov' AND [THIRD_NAME] = 'Kostov' AND [UCN] = '9953354231'
);
--


INSERT INTO [PHONE_NUMBERS] ([UPDATE_COUNTER], [PERSON_ID], [PHONE_TYPE_ID], [PHONE])
SELECT 0, p.ID, pt.ID, '0892458325'
FROM PERSONS p
CROSS JOIN PHONE_TYPES pt
WHERE p.FIRST_NAME = 'Georgi'
    AND pt.PHONE_TYPE = 'Work'
    AND NOT EXISTS (
        SELECT 1
        FROM [PHONE_NUMBERS]
        WHERE [PERSON_ID] = p.ID
            AND [PHONE_TYPE_ID] = pt.ID
    );


INSERT INTO [PHONE_NUMBERS] ([UPDATE_COUNTER], [PERSON_ID], [PHONE_TYPE_ID], [PHONE])
SELECT 0, p.ID, pt.ID, '0883421735'
FROM PERSONS p
JOIN PHONE_TYPES pt ON pt.PHONE_TYPE = 'Stationary'
WHERE p.FIRST_NAME = 'Tsvetelin'
    AND NOT EXISTS (
        SELECT 1
        FROM [PHONE_NUMBERS] pn
        WHERE pn.[PERSON_ID] = p.ID
            AND pn.[PHONE_TYPE_ID] = pt.ID
    );

-- Insert a phone number for "Veselin" if it doesn't already exist
INSERT INTO [PHONE_NUMBERS] ([UPDATE_COUNTER], [PERSON_ID], [PHONE_TYPE_ID], [PHONE])
SELECT 0, p.ID, pt.ID, '0892364375'
FROM PERSONS p
JOIN PHONE_TYPES pt ON pt.PHONE_TYPE = 'Home'
WHERE p.FIRST_NAME = 'Veselin'
    AND NOT EXISTS (
        SELECT 1
        FROM [PHONE_NUMBERS] pn
        WHERE pn.[PERSON_ID] = p.ID
            AND pn.[PHONE_TYPE_ID] = pt.ID
    );

-- Insert a phone number for "Aleksandar" if it doesn't already exist
INSERT INTO [PHONE_NUMBERS] ([UPDATE_COUNTER], [PERSON_ID], [PHONE_TYPE_ID], [PHONE])
SELECT 0, p.ID, pt.ID, '0894236548'
FROM PERSONS p
JOIN PHONE_TYPES pt ON pt.PHONE_TYPE = 'Mobile'
WHERE p.FIRST_NAME = 'Aleksandar'
    AND NOT EXISTS (
        SELECT 1
        FROM [PHONE_NUMBERS] pn
        WHERE pn.[PERSON_ID] = p.ID
            AND pn.[PHONE_TYPE_ID] = pt.ID
    );
BEGIN TRY 
	BEGIN TRANSACTION
		INSERT INTO [PERSONS] ([UPDATE_COUNTER], [FIRST_NAME], [SECOND_NAME], [THIRD_NAME], [UCN], [CITY_ID], [ADDRESS])
		SELECT 0, 'Martin', 'Kostov', 'Kostov', '8053354231', (SELECT ID FROM CITIES WITH(NOLOCK) WHERE [NAME]='Vraca'), 'Hristo Botev 82'
		WHERE NOT EXISTS (
		SELECT 1
		FROM [PERSONS]
		WHERE [FIRST_NAME] = 'Martin' AND [SECOND_NAME] = 'Kostov' AND [THIRD_NAME] = 'Kostov' AND [UCN] = '8053354231'
);
		INSERT INTO [PHONE_NUMBERS] ([UPDATE_COUNTER], [PERSON_ID], [PHONE_TYPE_ID], [PHONE])
		SELECT 0, p.ID, pt.ID, '0894246249'
		FROM PERSONS p
		JOIN PHONE_TYPES pt ON pt.PHONE_TYPE = 'Mobile'
		WHERE p.FIRST_NAME = 'Martin'
		AND NOT EXISTS (
		SELECT 1
		FROM [PHONE_NUMBERS] pn
		WHERE pn.[PERSON_ID] = p.ID
		AND pn.[PHONE_TYPE_ID] = pt.ID
    );

	COMMIT TRANSACTION
END TRY

BEGIN CATCH 
	ROLLBACK TRANSACTION
END CATCH



SELECT * FROM PERSONS



	
	




