
SELECT 
	CITIES.[NAME],
	PERSONS.FIRST_NAME
FROM CITIES WITH(NOLOCK)
INNER JOIN PERSONS
	ON CITIES.ID=PERSONS.ID
GO

SELECT 
	PERSONS.FIRST_NAME,
	PHONE_NUMBERS.PHONE,
	PERSONS.[ADDRESS]
FROM PERSONS WITH(NOLOCK)
FULL OUTER JOIN PHONE_NUMBERS
	ON PERSONS.ID=PHONE_NUMBERS.ID
GO
	
IF EXISTS (SELECT * FROM sys.views  WITH(NOLOCK) WHERE name = 'VI_PERSON_ABOVE_40_YEAR')
    DROP VIEW [VI_PERSON_ABOVE_40_YEAR];
GO
--VIEW 
CREATE VIEW [VI_PERSON_ABOVE_40_YEAR] AS
SELECT [FIRST_NAME], [THIRD_NAME], [ADDRESS],C.[NAME],LEFT(UCN, 2) AS BIRTH_YEAR
FROM PERSONS WITH(NOLOCK)
JOIN CITIES C ON PERSONS.[CITY_ID]=C.ID
WHERE CAST(LEFT(UCN, 2) AS INT) > 83;
GO

IF EXISTS (SELECT * FROM sys.views WITH(NOLOCK) WHERE name = 'VI_ALL_TOWN_COUNT_BY_SUBSCRIBER')
    DROP VIEW [VI_ALL_TOWN_COUNT_BY_SUBSCRIBER];
GO

CREATE VIEW [VI_ALL_TOWN_COUNT_BY_SUBSCRIBER] AS
SELECT CITIES.[NAME], COUNT(0) AS PEOPLE_COUNT
FROM PERSONS  WITH(NOLOCK)
JOIN CITIES ON PERSONS.[CITY_ID] = CITIES.ID
GROUP BY CITIES.[NAME];
GO

IF EXISTS (SELECT * FROM  sys.views WITH(NOLOCK) WHERE name = 'VI_YOUNG_THREE_PEOPLE_VARNA')
    DROP VIEW [VI_YOUNG_THREE_PEOPLE_VARNA];
GO

CREATE VIEW [VI_YOUNG_THREE_PEOPLE_VARNA] AS
WITH  CALCULATE_AGE AS
(
SELECT 
	PERSONS.FIRST_NAME, PERSONS.UCN,
    CASE
		 WHEN LEFT(PERSONS.UCN, 1) <> '0' THEN '19' + LEFT(PERSONS.UCN, 2)
		 ELSE '20' + LEFT(PERSONS.UCN, 2)
     END AS UCN_YEAR,
     YEAR(GETDATE()) - CAST
	 (
	 CASE
     WHEN LEFT(PERSONS.UCN, 1) <> '0' THEN '19' + LEFT(PERSONS.UCN, 2)
     ELSE '20' + LEFT(PERSONS.UCN, 2)
     END AS INT) AS PERSON_AGE
     FROM
        PERSONS WITH(NOLOCK)
    JOIN
        CITIES ON PERSONS.[CITY_ID] = CITIES.ID
    WHERE
        CITIES.[NAME] = 'Varna' 
)
SELECT TOP 3 *
FROM
    CALCULATE_AGE
ORDER BY
    PERSON_AGE ASC;
GO

SELECT * FROM [VI_ALL_TOWN_COUNT_BY_SUBSCRIBER] WITH(NOLOCK)











